### ISSUE TITLE
support SSH to fake ip

### ISSUE THREAD

**Issue by xuan2261** [soheil-js/MVNet_Old#2]
Can you update library MVNet to use type SSH fake ip?

**Comment by soheil-js** [comment]
> Can you update library MVNet to use type SSH fake ip?

This library uses the Rebex library.
I had to write such a library because the Rebex library did not support cookies before.
And this library does not support the SSH protocol, that this library is dedicated to the  HTTPS protocol.

**Comment by xuan2261** [comment]
is there any way to use ssh fake ip with this library?

**Comment by DarkneSsDz** [comment]
> ssh fake ip
what do you mean by that
